<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Resep extends Seeder
{
    public function run()
    {
        $data = [
            [
                "id_resep" => 1,
                "id_pengguna" => 2,
                "nama_resep" => "Nasi Goreng Spesial",
                "gambar" => "https://picsum.photos/234",
                "kategori" => "Makanan",
                "deskripsi" => "Resep lezat dan mudah dibuat.",
                "tanggal_unggah" => "2023-10-01",                
            ],
            [
                "id_resep" => 2,
                "id_pengguna" => 5,
                "nama_resep" => "Soto Ayam Lamongan",
                "gambar" => "https://picsum.photos/235",
                "kategori" => "Makanan",
                "deskripsi" => "Kuah segar, ayam empuk, nikmat!",
                "tanggal_unggah" => "2023-10-05",                
            ],
            [
                "id_resep" => 3,
                "id_pengguna" => 1,
                "nama_resep" => "Es Teh Manis Segar",
                "gambar" => "https://picsum.photos/236",
                "kategori" => "Minuman",
                "deskripsi" => "Minuman pelepas dahaga.",
                "tanggal_unggah" => "2023-10-10",                
            ],
            [
                "id_resep" => 4,
                "id_pengguna" => 3,
                "nama_resep" => "Pisang Goreng Crispy",
                "gambar" => "https://picsum.photos/237",
                "kategori" => "Makanan",
                "deskripsi" => "Makanan renyah teman santai.",
                "tanggal_unggah" => "2023-10-12",                
            ],
            [
                "id_resep" => 5,
                "id_pengguna" => 4,
                "nama_resep" => "Rendang Daging Sapi",
                "gambar" => "https://picsum.photos/238",
                "kategori" => "Makanan",
                "deskripsi" => "Masakan Padang otentik.",
                "tanggal_unggah" => "2023-10-15",                
            ],
            [
                "id_resep" => 6,
                "id_pengguna" => 2,
                "nama_resep" => "Jus Alpukat Creamy",
                "gambar" => "https://picsum.photos/239",
                "kategori" => "Minuman",
                "deskripsi" => "Sehat dan mengenyangkan.",
                "tanggal_unggah" => "2023-10-18",                
            ],
            [
                "id_resep" => 7,
                "id_pengguna" => 5,
                "nama_resep" => "Bakwan Sayur Udang",
                "gambar" => "https://picsum.photos/240",
                "kategori" => "Makanan",
                "deskripsi" => "Gorengan gurih dan nikmat.",
                "tanggal_unggah" => "2023-10-20",                
            ],
            [
                "id_resep" => 8,
                "id_pengguna" => 1,
                "nama_resep" => "Mie Goreng Jawa",
                "gambar" => "https://picsum.photos/241",
                "kategori" => "Makanan",
                "deskripsi" => "Dengan bumbu medok khas Jawa.",
                "tanggal_unggah" => "2023-10-22",                
            ],
            [
                "id_resep" => 9,
                "id_pengguna" => 3,
                "nama_resep" => "Ayam Bakar Madu",
                "gambar" => "https://picsum.photos/242",
                "kategori" => "Makanan",
                "deskripsi" => "Manis gurih meresap sempurna.",
                "tanggal_unggah" => "2023-10-25",                
            ],
            [
                "id_resep" => 10,
                "id_pengguna" => 4,
                "nama_resep" => "Kopi Susu Gula Aren",
                "gambar" => "https://picsum.photos/243",
                "kategori" => "Minuman",
                "deskripsi" => "Perpaduan kopi dan manisnya gula aren.",
                "tanggal_unggah" => "2023-10-28",                
            ],
            [
                "id_resep" => 11,
                "id_pengguna" => 2,
                "nama_resep" => "Martabak Manis Keju Coklat",
                "gambar" => "https://picsum.photos/244",
                "kategori" => "Makanan",
                "deskripsi" => "Lembut dan lumer di mulut.",
                "tanggal_unggah" => "2023-11-01",                
            ],
            [
                "id_resep" => 12,
                "id_pengguna" => 5,
                "nama_resep" => "Gado-Gado Siram",
                "gambar" => "https://picsum.photos/245",
                "kategori" => "Makanan",
                "deskripsi" => "Salad sayur dengan bumbu kacang.",
                "tanggal_unggah" => "2023-11-03",                
            ],
            [
                "id_resep" => 13,
                "id_pengguna" => 1,
                "nama_resep" => "Sayur Asem Jakarta",
                "gambar" => "https://picsum.photos/246",
                "kategori" => "Makanan",
                "deskripsi" => "Kuah segar dengan rasa asam pedas.",
                "tanggal_unggah" => "2023-11-05",                
            ],
            [
                "id_resep" => 14,
                "id_pengguna" => 3,
                "nama_resep" => "Smoothie Buah Naga Pisang",
                "gambar" => "https://picsum.photos/247",
                "kategori" => "Minuman",
                "deskripsi" => "Minuman sehat penuh vitamin.",
                "tanggal_unggah" => "2023-11-08",                
            ],
            [
                "id_resep" => 15,
                "id_pengguna" => 4,
                "nama_resep" => "Tahu Isi Pedas",
                "gambar" => "https://picsum.photos/248",
                "kategori" => "Makanan",
                "deskripsi" => "Pedasnya nampol, bikin nagih!",
                "tanggal_unggah" => "2023-11-10",                
            ],
            [
                "id_resep" => 16,
                "id_pengguna" => 2,
                "nama_resep" => "Ikan Bakar Jimbaran",
                "gambar" => "https://picsum.photos/249",
                "kategori" => "Makanan",
                "deskripsi" => "Bumbu meresap, daging ikan lembut.",
                "tanggal_unggah" => "2023-11-12",                
            ],
            [
                "id_resep" => 17,
                "id_pengguna" => 5,
                "nama_resep" => "Capcay Kuah Seafood",
                "gambar" => "https://picsum.photos/250",
                "kategori" => "Makanan",
                "deskripsi" => "Aneka sayuran dengan seafood segar.",
                "tanggal_unggah" => "2023-11-15",                
            ],
            [
                "id_resep" => 18,
                "id_pengguna" => 1,
                "nama_resep" => "Es Kelapa Muda Jeruk",
                "gambar" => "https://picsum.photos/251",
                "kategori" => "Minuman",
                "deskripsi" => "Kesegaran ganda kelapa dan jeruk.",
                "tanggal_unggah" => "2023-11-18",                
            ],
            [
                "id_resep" => 19,
                "id_pengguna" => 3,
                "nama_resep" => "Risoles Mayo Smoked Beef",
                "gambar" => "https://picsum.photos/252",
                "kategori" => "Makanan",
                "deskripsi" => "Lumer di mulut, gurihnya pas.",
                "tanggal_unggah" => "2023-11-20",                
            ],
            [
                "id_resep" => 20,
                "id_pengguna" => 4,
                "nama_resep" => "Pepes Tahu Jamur",
                "gambar" => "https://picsum.photos/253",
                "kategori" => "Makanan",
                "deskripsi" => "Aroma khas daun pisang, lezat.",
                "tanggal_unggah" => "2023-11-22",                
            ],
            [
                "id_resep" => 21,
                "id_pengguna" => 2,
                "nama_resep" => "Bubur Kacang Hijau Ketan Hitam",
                "gambar" => "https://picsum.photos/254",
                "kategori" => "Makanan",
                "deskripsi" => "Manis legit menghangatkan.",
                "tanggal_unggah" => "2023-11-25",                
            ],
            [
                "id_resep" => 22,
                "id_pengguna" => 5,
                "nama_resep" => "Wedang Jahe Sereh",
                "gambar" => "https://picsum.photos/255",
                "kategori" => "Minuman",
                "deskripsi" => "Minuman tradisional penghangat badan.",
                "tanggal_unggah" => "2023-11-28",                
            ],
            [
                "id_resep" => 23,
                "id_pengguna" => 1,
                "nama_resep" => "Cireng Bumbu Rujak",
                "gambar" => "https://picsum.photos/256",
                "kategori" => "Makanan",
                "deskripsi" => "Kenyal di dalam, crispy di luar.",
                "tanggal_unggah" => "2023-12-01",                
            ],
            [
                "id_resep" => 24,
                "id_pengguna" => 3,
                "nama_resep" => "Nasi Uduk Komplit",
                "gambar" => "https://picsum.photos/257",
                "kategori" => "Makanan",
                "deskripsi" => "Gurihnya nasi dengan lauk lengkap.",
                "tanggal_unggah" => "2023-12-03",                
            ],
            [
                "id_resep" => 25,
                "id_pengguna" => 4,
                "nama_resep" => "Sate Lilit Ayam Khas Bali",
                "gambar" => "https://picsum.photos/258",
                "kategori" => "Makanan",
                "deskripsi" => "Aroma rempah yang menggoda.",
                "tanggal_unggah" => "2023-12-05",                
            ],
            [
                "id_resep" => 26,
                "id_pengguna" => 2,
                "nama_resep" => "Thai Tea Original",
                "gambar" => "https://picsum.photos/259",
                "kategori" => "Minuman",
                "deskripsi" => "Rasa teh Thailand yang otentik.",
                "tanggal_unggah" => "2023-12-08",                
            ],
            [
                "id_resep" => 27,
                "id_pengguna" => 5,
                "nama_resep" => "Pastel Isi Sayur Ayam",
                "gambar" => "https://picsum.photos/260",
                "kategori" => "Makanan",
                "deskripsi" => "Renyah kulitnya, lezat isinya.",
                "tanggal_unggah" => "2023-12-10",                
            ],
            [
                "id_resep" => 28,
                "id_pengguna" => 1,
                "nama_resep" => "Rawon Daging Khas Surabaya",
                "gambar" => "https://picsum.photos/261",
                "kategori" => "Makanan",
                "deskripsi" => "Kuah hitam kluwek yang khas.",
                "tanggal_unggah" => "2023-12-12",                
            ],
            [
                "id_resep" => 29,
                "id_pengguna" => 3,
                "nama_resep" => "Tempe Mendoan Purwokerto",
                "gambar" => "https://picsum.photos/262",
                "kategori" => "Makanan",
                "deskripsi" => "Gorengan khas dengan sambal kecap.",
                "tanggal_unggah" => "2023-12-15",                
            ],
            [
                "id_resep" => 30,
                "id_pengguna" => 4,
                "nama_resep" => "Es Cincau Hijau Gula Merah",
                "gambar" => "https://picsum.photos/263",
                "kategori" => "Minuman",
                "deskripsi" => "Segar alami, manisnya pas.",
                "tanggal_unggah" => "2023-12-18",                
            ],
        ];

                $this->db->table('resep')->insertBatch($data);
    }
}